### ISSUE TITLE
感谢作者提供这么好的插件

### ISSUE THREAD

**Issue by pisceswb** [Yimien/plugin-memos-sync#1]
感谢作者提供这么好的插件，可用且非常好用。
提两个建议：
1. 把Memos分月份保存。例如2024年1月份的Memos，都放在“2024年1月”这个文档下，作为子文档。
2. 把图片后的回车符去掉。个人需求将图片宽度的默认值设成了33%，如果把图片后面的回车符去掉了的话，每行就能呈现3张图片了。

再次感谢作者提供这么好的插件，赞！👍

**Comment by pisceswb** [comment]
发现Memos不同段落间及图片间不是普通回车符（Enter），是手动换行符（Shift+Enter）。请问能否把图片间的手动换行符删除？

**Comment by Yimien** [comment]
关于第一点，Daily Note 保存的路径是读取笔记本配置的，如果你想要自定义路径，修改那里就可以了。
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/32ddcf71-7785-4952-b018-eb64dfce05c6)
然后是第二点，图片宽度这个应该是处理不了，或者说处理起来很麻烦，不过图片之间的换行符这个可以试试

**Comment by pisceswb** [comment]
谢谢！
没有使用Daily Note，想保存在一个普通文档下，按月份再分成子文档，这样清晰一些，也方便查找文件，当然这个同步完后，自己整理也行。
第二点，不需要更改图片宽度，在思源笔记中使用CSS能够更改插入图片的默认宽度。只需要您把图片之间的换行符去掉就行。

**Comment by pisceswb** [comment]
还有，您是不是忘记了把0.1.2版本上传到思源笔记的插件系统中？
从思源笔记中看到的插件版本还是0.1.0

**Comment by pisceswb** [comment]
文档分成月份，可能牵扯到第二次、第三次更新的Memos，是放到上一个月份的文件夹里，还是放到当前月份的文件夹中的问题。要不还是不分子文件了吧，自己分也挺方便的，请忽略掉这个提议。
再次感谢作者的辛苦付出，期待这个插件好久了👍👍👍

**Comment by Yimien** [comment]
> 谢谢！ 没有使用Daily Note，想保存在一个普通文档下，按月份再分成子文档，这样清晰一些，也方便查找文件，当然这个同步完后，自己整理也行。 第二点，不需要更改图片宽度，在思源笔记中使用CSS能够更改插入图片的默认宽度。只需要您把图片之间的换行符去掉就行。

如果你的最末级不是日而月的话，理论上daily note 也能做到，基本上只要你模板配置的对，就没问题

**Comment by Yimien** [comment]
> 还有，您是不是忘记了把0.1.2版本上传到思源笔记的插件系统中？ 从思源笔记中看到的插件版本还是0.1.0

这个是我忘记改配置文件的版本号，只要你能用就说明是正式版，昨天发布后我下下来试了来，发现插件初始化不了，才紧急修复了一版上去，然后也是没经验，不知道还要改版本号

**Comment by pisceswb** [comment]
请问0.1.3版本删除图片之间的换行符了吗？这个版本测试时，图片还是换行显示的呢

**Comment by pisceswb** [comment]
希望是这样的形式
![image](https://github.com/Yimien/plugin-memos-sync/assets/104658457/82bd3673-ab07-4350-9329-8cd5609acbd5)

**Comment by pisceswb** [comment]
另外可以将换行符由手动换行符（Shift+Enter）替换成普通的回车符（Enter），这样就不会形成思源笔记不建议使用的大段落块了
![image](https://github.com/Yimien/plugin-memos-sync/assets/104658457/01e90d6f-0f27-4c0e-957d-ce02347b0cb1)

**Comment by Yimien** [comment]
> 另外可以将换行符由手动换行符（Shift+Enter）替换成普通的回车符（Enter），这样就不会形成思源笔记不建议使用的大段落块了 ![image](https://private-user-images.githubusercontent.com/104658457/293951745-01e90d6f-0f27-4c0e-957d-ce02347b0cb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTEyNjcsIm5iZiI6MTcwNDM1MDk2NywicGF0aCI6Ii8xMDQ2NTg0NTcvMjkzOTUxNzQ1LTAxZTkwZDZmLTBmMjctNGMwZS05NTdkLWNlMDIzNDdiMGNiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQwNjQ5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDBmYjBmYzY4ODI3ZGY5NTJhMmIyZTQwZmYyNDlhYmFiMGM5YjBmNGJkYTNjNTBlMDY0NWRhZTc5NTk3Y2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F53wkqkuLJPqHG9nV2RjcH6LNQhgBrD0M4PkTUyYsSM)

新增了配置项，在设置里把图片布局改成横向，在调整过宽度后，布局效果大概是这样，哦，这是针对同步到DAILY NOTE的，另一种模式没有调整
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/8d47a7e5-dcd4-46d7-874a-aa2914d081e2)

**Comment by Yimien** [comment]
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/1e9c7c32-d5a3-4210-838a-0750a0bbfab6)
至于你说的换行符，在写入数据时，思源会根据自身的块类型进行划分，也就是说，比如假如文字和图片一起写入话，会被归为同一类，任何换行符都会被识别为在块内换行，而不会新增一个块。
目前是将所有的资源从文字块中提取出来，所有的图片统一放至同一个块，其它类型的资源一个链接一个块，因为图片统一一个块内，可以自由选择是横向还是纵向布局，默认是纵向布局

**Comment by pisceswb** [comment]
明白了，感谢解惑。我没有使用daily note模式，看你发的图，daily note能够把好几个Memos在同一个文档中显示，感觉这种方式好像更好，我也转成daily note模式试一下。

**Comment by pisceswb** [comment]
完美，非常好用，👍👍👍

**Comment by Yimien** [comment]
👌
