### ISSUE TITLE
iPhone及iPad上会报错

### ISSUE THREAD

**Issue by nscmiaoxin** [Yimien/plugin-memos-sync#10]
测试了好几次，在Macos的客户端上没有问题，docker环境下也没有问题，安卓上也没有问题
但是，在iOS及iPad上就会报错，配置完全相同，不知道为什么
![IMG_0353](https://github.com/Yimien/plugin-memos-sync/assets/44441301/fb36f8b1-bb10-43a9-a2d5-50cf9515a759)
![IMG_0503](https://github.com/Yimien/plugin-memos-sync/assets/44441301/f0cf137b-9122-4d33-b2bc-e94b23a96f49)

**Comment by Yimien** [comment]
没见过的错误啊，我手头上也没有ios设备，后面有空再研究一下吧

**Comment by nscmiaoxin** [comment]
> 没见过的错误啊，我手头上也没有ios设备，后面有空再研究一下吧

好的，感谢！非常奇怪的错误，连验证token的步骤都没有走到，就蹦出这个提示了，期待大神排查修复。

**Comment by Yimien** [comment]
> > 没见过的错误啊，我手头上也没有ios设备，后面有空再研究一下吧
> 
> 好的，感谢！非常奇怪的错误，连验证token的步骤都没有走到，就蹦出这个提示了，期待大神排查修复。

验证token和点击按钮开始同步后会报这个错吗？

**Comment by nscmiaoxin** [comment]
> > > 没见过的错误啊，我手头上也没有ios设备，后面有空再研究一下吧
> > 
> > 
> > 好的，感谢！非常奇怪的错误，连验证token的步骤都没有走到，就蹦出这个提示了，期待大神排查修复。
> 
> 验证token和点击按钮开始同步后会报这个错吗？

不是的，在iOS和Pados之下，填好token的瞬间就会出现这个错误，不用点击验证就会出现。
如果点击了✅，不去管它，过一会儿还会再次出现。
同样，划掉App后，再次打开App后，第一时间这个提示就会出现。

**Comment by Yimien** [comment]
报错应该和填token没有关系，因为在填token的时候，我后台是没有做任何操作的。
我对ios相关的开发并不熟悉，但查了下资料说可能和请求参数有关，只不过我手头上没有相关的设备，所以可能需要你这边一些帮助。
1. 先禁用插件，再启用，等待一段时候看看有没有相关的报错；
2. 在确保参数已经填写的情况下，点击校验按钮看看结果是否正常；

如果可以的话，尽量在打开思源笔记控制台的前提下进行上述操作，如果没办法打开控制台的话，看看能不能用设置页的打开浏览器去看到报错信息。
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/53561e6d-0799-4486-87d8-2c756a2dc521)

如果上述还不能找到问题的话，那就只能等我后面加个调试功能去尝试获取日志了看看断在哪一步了，只是这个东西可能没那么快出来就是了。

当然，如果你能自己解决然后PR上来，那就再好不过了。

**Comment by Yimien** [comment]
长时间没有反馈，先关了
