### ISSUE TITLE
同步报错

### ISSUE THREAD

**Issue by UltramarineSky** [Yimien/plugin-memos-sync#16]
同步时同步了一些就开始弹窗报`invalid ID argument`(ps：我之前删了一些没用的记录，不知道是不是因为这)，然后弹几次后就开始报错，无法继续同步

![image](https://github.com/Yimien/plugin-memos-sync/assets/54146035/44c694f8-58c3-47bc-8b6d-de3faab9d74a)

https://github.com/Yimien/plugin-memos-sync/issues/13#issue-2162610858
请问这个调试功能要怎么使用

**Comment by Yimien** [comment]
> 同步时同步了一些就开始弹窗报`invalid ID argument`(ps：我之前删了一些没用的记录，不知道是不是因为这)，然后弹几次后就开始报错，无法继续同步
> 
> ![image](https://private-user-images.githubusercontent.com/54146035/316838533-44c694f8-58c3-47bc-8b6d-de3faab9d74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTU2ODEsIm5iZiI6MTcxMTQ1NTM4MSwicGF0aCI6Ii81NDE0NjAzNS8zMTY4Mzg1MzMtNDRjNjk0ZjgtNThjMy00N2JjLThiNmQtZGUzZmFhYjlkNzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMTYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOGI0ZDY3M2JjYTI0ZGMyYzk4ZGU2NThiYzk2YjYxN2M0MjUxMGIxOGVlMjI1OWE3YjJlMTM2NGVmODI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GB3s5DFvnxVSitPn5PwLNxJyOO6vgOndXXgPKSLB7q4)
> 
> [#13 (comment)](https://github.com/Yimien/plugin-memos-sync/issues/13#issue-2162610858) 请问这个调试功能要怎么使用

不应该啊，我也有删过再同步，也没出现这个问题，能不能详细说明一下复现步骤，如果可以的话也提供一下控制台日志，至于调试功能还没加，预算中的调试功能也只是在控制台打印日志方便定位是在进行什么步骤时出的错

**Comment by UltramarineSky** [comment]
谢谢回复，使用时没什么特别的操作，点击同步后同步了些内容就开始报错，试过几次，开始报错的时候同步的记录不是同一条的
```
plugin:plugin-memos-sync:10 Uncaught (in promise) Error: TypeError: Cannot read properties of null (reading '0')
    at Wr.runSync (plugin:plugin-memos-sync:10:4766)
runSync @ plugin:plugin-memos-sync:10
```
下面是整个的
[127.0.0.1-1711457310488.log](https://github.com/Yimien/plugin-memos-sync/files/14758569/127.0.0.1-1711457310488.log)

**Comment by Yimien** [comment]
> 谢谢回复，使用时没什么特别的操作，点击同步后同步了些内容就开始报错，试过几次，开始报错的时候同步的记录不是同一条的
> 
> ```
> plugin:plugin-memos-sync:10 Uncaught (in promise) Error: TypeError: Cannot read properties of null (reading '0')
>     at Wr.runSync (plugin:plugin-memos-sync:10:4766)
> runSync @ plugin:plugin-memos-sync:10
> ```
> 
> 下面是整个的 [127.0.0.1-1711457310488.log](https://github.com/Yimien/plugin-memos-sync/files/14758569/127.0.0.1-1711457310488.log)

我这两天更新个调试模式吧，看看代码是断在哪一步

**Comment by Yimien** [comment]
> 谢谢回复，使用时没什么特别的操作，点击同步后同步了些内容就开始报错，试过几次，开始报错的时候同步的记录不是同一条的
> 
> ```
> plugin:plugin-memos-sync:10 Uncaught (in promise) Error: TypeError: Cannot read properties of null (reading '0')
>     at Wr.runSync (plugin:plugin-memos-sync:10:4766)
> runSync @ plugin:plugin-memos-sync:10
> ```
> 
> 下面是整个的 [127.0.0.1-1711457310488.log](https://github.com/Yimien/plugin-memos-sync/files/14758569/127.0.0.1-1711457310488.log)

调试功能已经更新了，你可以启用后看看执行到哪一步报错再把错误发给我看看

**Comment by 5kyfkr** [comment]
同样报一样的错误，看了下是已经获取到数据了，但是最后因为哪段代码报错了，补充下手机上又同步成功了，电脑我回家再试试：
![image](https://github.com/Yimien/plugin-memos-sync/assets/63196026/c931e397-5883-4914-ae82-a871f93d1cc3)
![image](https://github.com/Yimien/plugin-memos-sync/assets/63196026/ae749c13-16d9-40fe-bcb8-bbe8075d55bb)

**Comment by Yimien** [comment]
从提示上来看，应该是写入思源的时候报错了，但是缺少具体的数据，没办法判断是什么数据出的问题，你看下能不能私信提供下相关数据，如果不方便的话，也可以把原来的文档删除，再改下同步时间重新同步

**Comment by 5kyfkr** [comment]
> 从提示上来看，应该是写入思源的时候报错了，但是缺少具体的数据，没办法判断是什么数据出的问题，你看下能不能私信提供下相关数据，如果不方便的话，也可以把原来的文档删除，再改下同步时间重新同步

你试试用思源最新的3.0.6dev2开发版，试了好像是用了开发版就报错，已确认，3.0.5没这样，公司是dev1所以也会报错，家里的刚3.0.5还行，升dev2就不行了，备注：同步方式是同步到一个文档下面，重新同步到新文档也会报错。

翻了下更新说明，会不会这个影响了https://ld246.com/article/1711453114763

**Comment by UltramarineSky** [comment]
[127.0.0.1-1711629825711.log](https://github.com/Yimien/plugin-memos-sync/files/14789596/127.0.0.1-1711629825711.log)
用的3.0.6dev2开发版，选择同步到单份文档中报错，第二种同步方式单个文档下没问题。
用的memos数据是新创的一个用户，随便弄了20多条

**Comment by 5kyfkr** [comment]
> [127.0.0.1-1711629825711.log](https://github.com/Yimien/plugin-memos-sync/files/14789596/127.0.0.1-1711629825711.log) 用的3.0.6dev2开发版，选择同步到单份文档中报错，第二种同步方式单个文档下没问题。 用的memos数据是新创的一个用户，随便弄了20多条

这么神奇，我等下也新建个账号试试

**Comment by 5kyfkr** [comment]
> [127.0.0.1-1711629825711.log](https://github.com/Yimien/plugin-memos-sync/files/14789596/127.0.0.1-1711629825711.log) 用的3.0.6dev2开发版，选择同步到单份文档中报错，第二种同步方式单个文档下没问题。 用的memos数据是新创的一个用户，随便弄了20多条

试了，确实第二种可以，但是我还是喜欢同步到单个文档，能修复吗？感谢大佬

**Comment by Yimien** [comment]
试了下，确实测试版会出现，我先看看是什么问题，一般来说，测试版出现的问题是不修复的，因为不能确定在正式版上还会不会出现，总之我先看看是什么原因吧

**Comment by 5kyfkr** [comment]
> 试了下，确实测试版会出现，我先看看是什么问题，一般来说，测试版出现的问题是不修复的，因为不能确定在正式版上还会不会出现，总之我先看看是什么原因吧

已经两个测试版都出现了，应该会进入正式版的

**Comment by Yimien** [comment]
> > 试了下，确实测试版会出现，我先看看是什么问题，一般来说，测试版出现的问题是不修复的，因为不能确定在正式版上还会不会出现，总之我先看看是什么原因吧
> 
> 已经两个测试版都出现了，应该会进入正式版的

排查了一下，是思源的api出问题了，`/api/block/insertBlock` 这个接口如果使用的参数是 `nextID` 或者 `previousID` 就会报错，目前我这里处理不了，就先不动了，如果你们实在想要用的话可以去联系一下思源官方，当然如果确定就是要修改api，那我也得等他们更新api文档我才能改

**Comment by 5kyfkr** [comment]
> 排查了一下，是思源的api出问题了，`/api/block/insertBlock` 这个接口如果使用的参数是 `nextID` 或者 `previousID` 就会报错，目前我这里处理不了，就先不动了，如果你们实在想要用的话可以去联系一下思源官方，当然如果确定就是要修改api，那我也得等他们更新api文档我才能改

@88250 D大帮忙看看能不能修一下，3.0.6才出现的

**Comment by 88250** [comment]
@Yimien 麻烦发一下 insertBlock 的参数。

**Comment by Yimien** [comment]
> @Yimien 麻烦发一下 insertBlock 的参数。

@88250 

请求参数如下：
```json
{
  "dataType": "markdown",
  "data": "Memos列表",
  "nextID": "20240329113502-jx093q7"
}
```

如果是最新正式版，响应结果如下：
```json
{
    "code": 0,
    "msg": "",
    "data": [
        {
            "timestamp": 0,
            "doOperations": [
                {
                    "action": "insert",
                    "data": "<div data-node-id=\"20240329113524-fs7ox4o\" data-node-index=\"1\" data-type=\"NodeParagraph\" class=\"p\" updated=\"20240329113524\"><div contenteditable=\"true\" spellcheck=\"false\">Memos列表</div><div class=\"protyle-attr\" contenteditable=\"false\">​</div></div>",
                    "id": "20240329113524-fs7ox4o",
                    "parentID": "20240329113502-o6vxahq",
                    "previousID": "",
                    "nextID": "20240329113502-jx093q7",
                    "retData": null,
                    "blockIDs": null,
                    "blockID": "",
                    "deckID": "",
                    "avID": "",
                    "srcIDs": null,
                    "isDetached": false,
                    "ignoreFillFilter": false,
                    "name": "",
                    "type": "",
                    "format": "",
                    "keyID": "",
                    "rowID": "",
                    "isTwoWay": false,
                    "backRelationKeyID": ""
                }
            ],
            "undoOperations": null
        }
    ]
}
```

如果是开发版，响应结果就是这样了
```json
{
    "code": -1,
    "msg": "invalid ID argument",
    "data": null
}
```

除了 `nextID`外，如果使用 `previousID` 也会报一样的错，但同样的参数在正式版中返回的响应结果就是正常的。

**Comment by 88250** [comment]
收到，是个 bug，下个 dev 修复，多谢。
