### ISSUE TITLE
handleTag的匹配规则过于宽泛，容易把文本内的#都识别为tag

### ISSUE THREAD

**Issue by cubarco** [Yimien/plugin-memos-sync#18]
handleTag目前的实现会导致下面几种文本被识别为tag：
 1. URL锚点：`https://example.com/1/#test/one/two` ---> `https://example.com/1/#test/one/two# `
 2. 注释： `# test` ---> `##  test`
 
解决办法想了两个，一个是改善正则，有点复杂；另一个是按照我的使用习惯，只有最后一行会出现tag，所以只对最后一行handleTag。
这是第二种方案的代码：
```javascript
handleTag(content) {
  const regex = /(?<=#).*?(?=\s|#|$)/g; // 标签匹配规则

  let configData = this.data[STORAGE_NAME]; // 读取配置
  let labelName = configData.superLabelText;
  let lines = content.split("\n"); // Split the content into lines
  let lastLine = lines.pop(); // Pop the last line

  // Process only the last line based on superLabelMode
  if (configData.superLabelMode === sMaps.IS_USE.yes) {
    lastLine = lastLine.replace(regex, (match) => `${labelName}/${match}# `);
  } else {
    lastLine = lastLine.replace(regex, (match) => `${match}# `);
  }

  // Reconstruct the content including the processed last line
  let result = [...lines, lastLine].join("\n");

  return result;
}
```

**Comment by Yimien** [comment]
> handleTag目前的实现会导致下面几种文本被识别为tag：
> 
> 1. URL锚点：`https://example.com/1/#test/one/two` ---> `https://example.com/1/#test/one/two# `
> 2. 注释： `# test` ---> `##  test`
> 
> 解决办法想了两个，一个是改善正则，有点复杂；另一个是按照我的使用习惯，只有最后一行会出现tag，所以只对最后一行handleTag。 这是第二种方案的代码：
> 
> ```js
> handleTag(content) {
>   const regex = /(?<=#).*?(?=\s|#|$)/g; // 标签匹配规则
> 
>   let configData = this.data[STORAGE_NAME]; // 读取配置
>   let labelName = configData.superLabelText;
>   let lines = content.split("\n"); // Split the content into lines
>   let lastLine = lines.pop(); // Pop the last line
> 
>   // Process only the last line based on superLabelMode
>   if (configData.superLabelMode === sMaps.IS_USE.yes) {
>     lastLine = lastLine.replace(regex, (match) => `${labelName}/${match}# `);
>   } else {
>     lastLine = lastLine.replace(regex, (match) => `${match}# `);
>   }
> 
>   // Reconstruct the content including the processed last line
>   let result = [...lines, lastLine].join("\n");
> 
>   return result;
> }
> ```

 谢谢反馈，我个人也是习惯在最后一行打标签，但总有人不一样，所以才改为全局匹配，不过你说的问题也不能忽略，这样吧，我再加个设置
