### ISSUE TITLE
Memos v0.21.0 同步失败

### ISSUE THREAD

**Issue by beijixiaohu** [Yimien/plugin-memos-sync#19]
作者你好，Memos 官方在 v0.21.0 中弃用了 v1 版本的 API，[详见](https://github.com/usememos/memos/tree/404751f378fe5f3e3fb8b1bffcb9444445aab5c4/server/route/api/v1)

现在 get `/api/v1/ping` 会返回一个HTML网页

**Comment by Yimien** [comment]
> 作者你好，Memos 官方在 v0.21.0 中弃用了 v1 版本的 API，[详见](https://github.com/usememos/memos/tree/404751f378fe5f3e3fb8b1bffcb9444445aab5c4/server/route/api/v1)
> 
> 现在 get `/api/v1/ping` 会返回一个HTML网页

刚刚试了下，我这里调用 /api/v1/ping 接口返回的结果是正常的，至于api版本的问题，我后面找个时间再调整一下

**Comment by beijixiaohu** [comment]
> > 作者你好，Memos 官方在 v0.21.0 中弃用了 v1 版本的 API，[详见](https://github.com/usememos/memos/tree/404751f378fe5f3e3fb8b1bffcb9444445aab5c4/server/route/api/v1)
> > 现在 get `/api/v1/ping` 会返回一个HTML网页
> 
> 刚刚试了下，我这里调用 /api/v1/ping 接口返回的结果是正常的，至于api版本的问题，我后面找个时间再调整一下

今天试了下又可以了，应该是我的问题，谢谢作者

**Comment by netdog2019** [comment]
你图片同步过来正常吗？

> > > 作者你好，Memos 官方在 v0.21.0 中弃用了 v1 版本的 API，[详见](https://github.com/usememos/memos/tree/404751f378fe5f3e3fb8b1bffcb9444445aab5c4/server/route/api/v1)
> > > 现在 get `/api/v1/ping` 会返回一个HTML网页
> > 
> > 
> > 刚刚试了下，我这里调用 /api/v1/ping 接口返回的结果是正常的，至于api版本的问题，我后面找个时间再调整一下
> 
> 今天试了下又可以了，应该是我的问题，谢谢作者

**Comment by beijixiaohu** [comment]
> 你图片同步过来正常吗？

@netdog2019 不正常，图片显示不了
