### ISSUE TITLE
MEMOS 服务器端0.21，图片同步到思源笔记里无法显示，应该是图片获取失败

### ISSUE THREAD

**Issue by netdog2019** [Yimien/plugin-memos-sync#20]
MEMOS 服务器端0.21，图片同步到思源笔记里无法显示，应该是图片获取失败
其他内容正常，就是图片获取失败。
![image](https://github.com/Yimien/plugin-memos-sync/assets/49815951/f717cd00-2036-4cbd-a16a-a77a19c2bd33)

**Comment by Yimien** [comment]
memos 又改资源链接了，已经发布修复了，等插件市场更新吧

**Comment by netdog2019** [comment]
大佬威武~~感谢感谢~~~
