### ISSUE TITLE
3.0.10 ios移动设备打开此插件提示：TypeError Load Failed

### ISSUE THREAD

**Issue by code-lixm** [Yimien/plugin-memos-sync#22]

**Comment by Yimien** [comment]
能不能打开调试开关看一下控制台日志

> _No description provided._

**Comment by code-lixm** [comment]
检查了一下是safari的跨源策略限制，导致 api/ping 接口在跨域
<img width="1440" alt="image" src="https://github.com/Yimien/plugin-memos-sync/assets/42863578/12a00d56-e7ea-49de-b7ec-f47e835fd78e">
在mac上面需要手动打开停用跨源限制，ios的APP内部应该使用的是safari的webview渲染加载的，所以出现了同样的问题，现在可能比较靠谱的办法是：修改plugin.json, 只允许在docker，desktop，web上面使用，关闭手机端入口

**Comment by Yimien** [comment]
我猜也是这样，不过我以前有查到说配置 `Access-Control-Allow-Origin` 可以解决，但是手里没有设备不能验证，所以就一直没处理，我下次限制一下可用的客户端吧
