### ISSUE TITLE
Uncaught (in promise) Error: TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by zhuxiucai** [Yimien/plugin-memos-sync#23]
<img width="1650" alt="image" src="https://github.com/Yimien/plugin-memos-sync/assets/10626025/25573886-a94e-4619-a46f-d331b8c27f90">

**Comment by Yimien** [comment]
你这个插件的版本好像不太对，调试日志里的`标签处理完成`这个信息在现在的版本里移除了，等我更新一个版本后，你再试试看还会不会报错

**Comment by Yimien** [comment]
长时间没有反馈，先关了
