### ISSUE TITLE
memos升级0.22后不行了

### ISSUE THREAD

**Issue by zhuxiucai** [Yimien/plugin-memos-sync#24]
<img width="1663" alt="image" src="https://github.com/Yimien/plugin-memos-sync/assets/10626025/ac192c0f-45db-40a3-ad53-e12a04e314c1">

**Comment by Yimien** [comment]
目前官方的版本是0.21，官方推荐追的是stable标签，所以这个问题就先不处理，如果stable出问题了我再看看怎么解决

**Comment by WyInnovate** [comment]
同0.22

**Comment by Yimien** [comment]
v0.22 官方弃用V1接口

**Comment by zhuxiucai** [comment]
<img width="981" alt="image" src="https://github.com/Yimien/plugin-memos-sync/assets/10626025/5bc0ad80-10cf-4264-810f-19bcfe422f54">

**Comment by Yimien** [comment]
新的API我昨天研究了下，虽然是以v1开头，但是实质上就是原先的v2，接口全变了，响应结果也和原先的不一样，换句话说就是，更换API就相当于重写整个插件

**Comment by zhuxiucai** [comment]
辛苦了大佬。
上游变了，确实下游也受影响。理解给您增加的工作量的！

这个咱插件的核心价值，对siyuan可谓是相当重要，不着急，咱有时间再改。

如果实在没空，那就只好先不用memos了～

谢谢大佬回应！

**Comment by Yimien** [comment]
我估计以后会重写一个插件，不会在这个插件上改，因为当时做的时候没想到后续的这么多问题，特别是这次的API换代，想要改动的话有点太困难了，现在我能给的建议就是先不要升了。memos这次接口改得太大，而且调用写法比原先麻烦，需要花一定的时间研究，还有的一个问题就是，我发现我虽然写了这个插件，但是我使用memos的频率好像没想象中的那么高😅

**Comment by WyInnovate** [comment]
确实，我一直在用memos，但是使用频率不高，然后memos的api经常会变，从0.14变到现在的0.22都改了好几版本了，然后现在还有个问题是，如果你想从0.22回退到0.21，你需要用你自己备份的0.21的db文件去还原，直接回退版本是不行的！

**Comment by Yimien** [comment]
新版插件已发布
