### ISSUE TITLE
插件设置UI空白

### ISSUE THREAD

**Issue by oyacmtd56** [Yimien/plugin-memos-sync#25]
### 问题描述
1. 启用插件弹出错误通知，控制台也有报错。这个应该是符合预期的错误，此时未配置任何设置项
2. 点击插件设置时，弹出窗口但是窗体空白，控制台有报错信息，参考截图
![o25d3qbp wrb](https://github.com/Yimien/plugin-memos-sync/assets/122616278/65d16c4f-3f75-49d6-a54f-c06c9d1c6c0c)

### 环境及版本
siyuan kernel version: v3.0.13
plugin-memos-sync version: v0.2.2
browser version: MS Edge v124.0.2478.80

**Comment by Yimien** [comment]
这个我昨天发现了，还在找原因

**Comment by leeima** [comment]
> 这个我昨天发现了，还在找原因

我今天第一次用，正好赶上bug，辛苦大佬修复

**Comment by Yimien** [comment]
@88250

D大，我想问一下，我重写了openSetting方法，具体代码如下：
```
async openSetting() {
    this.nowNotebooks = await this.getNotebooks();
    super.openSetting();
  }
```

现在打开设置时，控制台会报错，插件设置页面空白
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/a71def2f-29a6-4637-bd5b-a69a20a4ac15)

控制台报错原因如下：
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tagName')
```

我定位到的最外层代码是 `super.openSetting();` 
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/90768921-100e-4825-8fc6-52990b2f6b1f)

最里层是
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/6b6b8ab5-e8e1-4ff3-a47c-a947679d0672)

所以我想问下，是不是有版本更新的时候改动到上图的位置，因为之前是没问题，如果有的话，您看下这是Bug，还是说我调用的方法需要修改

**Comment by 88250** [comment]
@Vanessa219 抽空帮忙看看。

**Comment by Vanessa219** [comment]
由于 https://github.com/siyuan-note/siyuan/pull/11214 造成的，可以先设置一下 `direction:"row"` 顶顶，目前已经发版本，否则只能等下个版本了。

**Comment by Yimien** [comment]
@Vanessa219 

V姐，我翻了一遍相关的issue，还是不知道怎么修改，请问 `direction:"row"` 是在哪里修改？

**Comment by frostime** [comment]
> @Vanessa219
> 
> V姐，我翻了一遍相关的issue，还是不知道怎么修改，请问 `direction:"row"` 是在哪里修改？

this.setting.addItem 里面

https://github.com/siyuan-note/petal/blob/4dc3d9b80ee8a2a468384cce96c5d3de918c1eb5/siyuan.d.ts#L588

**Comment by Yimien** [comment]
> > @Vanessa219
> > V姐，我翻了一遍相关的issue，还是不知道怎么修改，请问 `direction:"row"` 是在哪里修改？
> 
> this.setting.addItem 里面
> 
> https://github.com/siyuan-note/petal/blob/4dc3d9b80ee8a2a468384cce96c5d3de918c1eb5/siyuan.d.ts#L588

感谢大佬，问题解决了
