### ISSUE TITLE
mac端好像是能正常使用的，下个版本更新解开mac端限制吧

### ISSUE THREAD

**Issue by C-a-r-r-y** [Yimien/plugin-memos-sync#26]
我手动改了plugin.json，mac端试了一下好像是正常的

**Comment by Yimien** [comment]
好

**Comment by haiwz** [comment]
请问启用苹果芯片的mac代码是什么？

**Comment by C-a-r-r-y** [comment]
貌似是通用的都是darwin
我现在用的是
`  "backends": [
    "windows",
    "linux",
    "darwin",
    "android"
  ],
  "frontends": [
    "desktop",
    "mobile",
    "browser-desktop",
    "browser-mobile",
    "desktop-window"
  ],`

**Comment by haiwz** [comment]
感谢！
能打开，但是同步的时候提示HTTP错误，不适配思源3.0.15了

**Comment by C-a-r-r-y** [comment]
我手头上测试没问题，是不是你的memos更了0.22

**Comment by haiwz** [comment]
是的，重新安装了一下。可能是这个问题

**Comment by Yimien** [comment]
新版插件已发布
