### ISSUE TITLE
希望在memos里记录里写的引用[[此处是引用]]，在同步到思源里后能自动跟思源里的引用链接起来。

### ISSUE THREAD

**Issue by netdog2019** [Yimien/plugin-memos-sync#3]
希望在memos里记录里写的引用[[此处是引用]]，在同步到思源里后能自动跟思源里的引用链接起来。
不知道表达清楚没有，感谢这么好的插件，自从昨天用了以后，一发不可收拾，用手机随手都在写。

**Comment by Yimien** [comment]
这个我一开始有想做，但后面发现做不了，思源api不支持识别 [[ ]] 这个语法，思源本身在使用 `[[` 的时候如果引用的页面不存在会强制要求新建，否则就不认为是引用，这和obsidian不一样，因此，在api里面，只要是使用 [[ ]] 的字段都会被统一识别成文本
