### ISSUE TITLE
memos 同步失败

### ISSUE THREAD

**Issue by LEON121** [Yimien/plugin-memos-sync#4]
配置时候校验通过
![image](https://github.com/Yimien/plugin-memos-sync/assets/37445848/c7e6492a-cc48-49a5-aa1d-b17a46d6ef70)
但是同步时提示 token 错误
![image](https://github.com/Yimien/plugin-memos-sync/assets/37445848/0399a6c5-8dac-4b86-8b3c-43eec15d9185)

**Comment by Yimien** [comment]
已修复
