### ISSUE TITLE
思源 v2.12.3 同步失败

### ISSUE THREAD

**Issue by lechengyu** [Yimien/plugin-memos-sync#5]
<img width="709" alt="image" src="https://github.com/Yimien/plugin-memos-sync/assets/17262681/3577d3f8-a520-440d-83a3-952e55e613a8">

token检验通过，同步不了。

**Comment by Yimien** [comment]
你这个问题我这里复现不了，在思源笔记软件按下ctrl+shift+i，截一下控制台，或者可以先试下刚发布的最新版本

**Comment by lechengyu** [comment]
> 你这个问题我这里复现不了，在思源笔记软件按下ctrl+shift+i，截一下控制台，或者可以先试下刚发布的最新版本

更新了刚刚发布的最新版以后，可以同步了，感谢更新

**Comment by Yimien** [comment]
👌
