### ISSUE TITLE
能否将从memos导入时的标签自动添加一个上级标签？

### ISSUE THREAD

**Issue by flyingnight** [Yimien/plugin-memos-sync#6]
您好，如题，能否将从memos导入时的标签自动添加一个上级标签？
我的memos有几十个标签，导入后一下子让我的标签库变成一团乱麻，一下子多了几十个一级标签，管理很混乱，还把我原来的标签体系打乱了，很难找了。
希望可以在同步的时候自动将导入的标签改成二级标签，比如标签 #电影  ，导入后为 #memos/电影 ，这样在标签库很好管理了，一级标签的memos也可以自定义。
很希望大佬修改这个，或者可以选择是否创建二级标签。

**Comment by Yimien** [comment]
这个倒是可以，也不麻烦，如果急着用的话，可以在memos记录时，先自己划分两级
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/788b1ba1-46a3-4f0d-993c-54699087ca09)
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/ef624825-c45d-4219-a120-cfdf9c816097)
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/04c39f27-34e1-4f45-87aa-78d24e85e0c1)
