### ISSUE TITLE
勾选识别双向链接保存失败

### ISSUE THREAD

**Issue by dengxuezhao** [Yimien/plugin-memos-sync#7]
将该选项选择为是的时候，保存会提示有必填项没有填完。
![image](https://github.com/Yimien/plugin-memos-sync/assets/43956952/feb1b096-61de-4aad-a4fb-aa6cbf0fc563)

**Comment by Yimien** [comment]
下面的主题路径填了吗

**Comment by Yimien** [comment]
不过说起来也对，主题路径这个好像一开始就是允许为空的，我改下吧
