### ISSUE TITLE
memos服务升级到0.19后，内部的数据格式好像修改了，同步到思源无法显示图片。

### ISSUE THREAD

**Issue by netdog2019** [Yimien/plugin-memos-sync#8]
memos服务升级到0.19后，内部的数据格式好像修改了，同步到思源无法显示图片。

**Comment by netdog2019** [comment]
https://github.com/usememos/memos/releases/tag/v0.19.0

This release contains upgrade notes that deviate from the norm:

Requires database migrations;
Use short UUIDs instead of auto-incrementing IDs for memo and resource in API and frontend;
The docker image tag latest will be deprecated, use stable instead;

**Comment by Yimien** [comment]
最新版的同步插件已经做兼容了，你可以看一下更新日志
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/974cc9ec-2378-4a60-b729-e58eb39df7b0)
因为考虑到可能有人还没更新，所以需要自己手动配置一下
![image](https://github.com/Yimien/plugin-memos-sync/assets/42413155/c9a0d746-41b6-4144-a055-35636f9afca8)
