### ISSUE TITLE
在memos网页端插入的视频文件，希望同步到思源时能作为视频文件插入

### ISSUE THREAD

**Issue by netdog2019** [Yimien/plugin-memos-sync#9]
感谢大佬得精彩插件，在memos网页端插入的视频文件，希望同步到思源时能作为视频文件插入，这样视频文件可以在思源里直接显示，我看现在只是作为一个附件放进来，只是一个链接，不知道能否做成以视频插入的形式导入。

再次感谢。

**Comment by Yimien** [comment]
这个可以考虑，我有空研究一下吧
